const books = [
{id:1,title:"The Photographer's",author:"Lindsay Adler",genre:"Photography",price:300},
{id:2,title:"Churchill: A Life",author:"Martin Gilbert",genre:"Biography",price:400},
{id:3,title:"Harry Potter and The Order of The Phoenix",author:"J.K. Rowling",genre:"Fiction",price:500},
{id:4,title:"My Experiments with Truth",author:"Mahatma Gandhi",genre:"Autobiography",price:350},
{id:5,title:"Barracoon",author:"Zora Neale Hurston",genre:"Biography",price:320},
{id:6,title:"The Book Thief",author:"Markus Zusak",genre:"Story",price:300},
{id:7,title:"A Brief History Of Time",author:"Stephen Hawking",genre:"Science",price:450},
{id:8,title:"Mein Kampf",author:"Adolf Hitler",genre:"Autobiography",price:350},
{id:9,title:"Harry Potter and The Deathly Hallows",author:"J.K. Rowling",genre:"Fiction",price:550},
{id:10,title:"Alexander Hamilton",author:"Ron Chernow",genre:"Biography",price:400},
{id:11,title:"The Lord Of Wings",author:"J.R.R. Tolkien",genre:"Story",price:350},
{id:12,title:"Kidnapped",author:"Robert Louis",genre:"Fiction",price:300},
{id:13,title:"Loara Dune",author:"R. D Blackmore",genre:"Fiction",price:320},
{id:14,title:"A Beautiful Mind",author:"Sylvia Nasar",genre:"Biography",price:400},
{id:15,title:"The Enigma",author:"Andrew Hodges",genre:"Biography",price:380},
{id:16,title:"Discovery of India",author:"Jawaharlal Nehru",genre:"History",price:450},
{id:17,title:"Harry Potter and The Half-Blood Prince",author:"J.K. Rowling",genre:"Fiction",price:500},
{id:18,title:"Lord Of Flies",author:"William Golding",genre:"Fiction",price:350},
{id:19,title:"Wings Of Fire",author:"APJ Abdul Kalam",genre:"Autobiography",price:400},
{id:20,title:"Jamacia Inn",author:"Daphne",genre:"Fiction",price:320},
{id:21,title:"The Secrets of Dumbledore",author:"J.K. Rowling",genre:"Fiction",price:500},
{id:22,title:"Python For All",author:"John Shovic",genre:"Education",price:450},
{id:23,title:"Think and Grow Rich",author:"Napoleon Hill",genre:"Economics",price:350},
{id:24,title:"I Know Why The Cage Bird Sings",author:"Maya Angelou",genre:"Story",price:300},
{id:25,title:"The Wind In Willows",author:"Kenneth Grahame",genre:"Fiction",price:320},
{id:26,title:"Ikigai",author:"Hector Garcia",genre:"Personal Development",price:300},
{id:27,title:"City of Heavenly Fire",author:"Cassandra Clare",genre:"Fiction",price:400},
{id:28,title:"Automate The Boring Stuff With Python",author:"Al Sweigart",genre:"Education",price:500},
{id:29,title:"Over The Edge Of The World",author:"Laurence",genre:"History",price:350},
{id:30,title:"Thinking with Type",author:"Ellen Lupton",genre:"Arts",price:300},
{id:31,title:"The Republic",author:"Plato",genre:"Philosophy",price:300},
{id:32,title:"The Diary Of Young Girl",author:"Anne Frank",genre:"Autobiography",price:350},
{id:33,title:"Rich Dad Poor Dad",author:"Robert Kiyosaki",genre:"Business",price:400},
{id:34,title:"The Black Swan",author:"Nassim Taleb",genre:"Economics",price:350},
{id:35,title:"A World Lit Only By Fire",author:"William Manchester",genre:"History",price:380},
{id:36,title:"Being and Time",author:"Martin Heidegger",genre:"Philosophy",price:450},
{id:37,title:"Long Walk To Freedom",author:"Nelson Mandela",genre:"Autobiography",price:400},
{id:38,title:"The Call Of Wild",author:"Jack London",genre:"Fiction",price:300},
{id:39,title:"OOP with C++",author:"E Balagurusamy",genre:"Education",price:450},
{id:40,title:"Animal Spirits",author:"Akerlof & Shiller",genre:"Economics",price:350},
{id:41,title:"Harry Potter and The Prisoner of Azkaban",author:"J.K. Rowling",genre:"Fiction",price:500},
{id:42,title:"A Tale of Two Cities",author:"Charles Dickens",genre:"History",price:350},
{id:43,title:"Les Miserables",author:"Victor Hugo",genre:"History",price:450},
{id:44,title:"Harry Potter and The Chamber of Secrets",author:"J.K. Rowling",genre:"Fiction",price:500},
{id:45,title:"Kite Runner",author:"Khaled Hosseini",genre:"Story",price:350},
{id:46,title:"Da Vinci Code",author:"Dan Brown",genre:"Fiction",price:400},
{id:47,title:"The Fifth Discipline",author:"Peter Senge",genre:"Management",price:450},
{id:48,title:"Steve Jobs",author:"Walter Isaacson",genre:"Biography",price:500},
{id:49,title:"Ethics",author:"Stuart Hampshire",genre:"Philosophy",price:300},
{id:50,title:"Harry Potter and The Philosopher Stone",author:"J.K. Rowling",genre:"Fiction",price:500},
{id:51,title:"Treasure Island",author:"Robert Louis",genre:"Fiction",price:300},
{id:52,title:"Harry Potter and The Goblet of Fire",author:"J.K. Rowling",genre:"Fiction",price:550},
{id:53,title:"Who Will Cry When You Die",author:"Robin Sharma",genre:"Personal Development",price:300},
{id:54,title:"The Prince",author:"Rufus Godwin",genre:"Philosophy",price:350},
{id:55,title:"Immortals of Meluha",author:"Amish Tripathi",genre:"Fantasy",price:450},
{id:56,title:"War and Peace",author:"Leo Tolstoy",genre:"Fiction",price:500},
{id:57,title:"Critique of Pure Reason",author:"Paul Guyer",genre:"Philosophy",price:450},
{id:58,title:"Freakonomics",author:"Levitt",genre:"Economics",price:350},
{id:59,title:"Harry Potter and The Cursed Child",author:"J.K. Rowling",genre:"Fiction",price:500},
{id:60,title:"Guns Germs and Steel",author:"Jared Diamond",genre:"History",price:450},
{id:61,title:"Charlotte Web",author:"E.B White",genre:"Fiction",price:300},
{id:62,title:"Mark Twain",author:"Mark Twain",genre:"Autobiography",price:350},
{id:63,title:"A Theory of Justice",author:"John Rawls",genre:"Law",price:450},
{id:64,title:"History Of 20th Century",author:"Martin Gilbert",genre:"History",price:400},
{id:65,title:"Eat to Live",author:"Joel Fuhrman",genre:"Health",price:300},
{id:66,title:"Thinking Fast and Slow",author:"Daniel Kahneman",genre:"Economics",price:400},
{id:67,title:"Tell You About Capitalism",author:"Ha-Joon Chang",genre:"Economics",price:350},
{id:68,title:"The Crusades",author:"Thomas Asbridge",genre:"History",price:450}
];